# ===== Servidor =====
server.port=8081

# ===== Base de datos PostgreSQL =====
spring.datasource.url=jdbc:postgresql://localhost:5432/veterinaria_db
spring.datasource.username=postgres
spring.datasource.password=joss
spring.datasource.driver-class-name=org.postgresql.Driver

# ===== Thymeleaf =====
spring.thymeleaf.cache=false

# ===== Logging =====
logging.level.org.springframework.security=INFO
